export type IntroTechItem = {
  icon: string;
  label: string;
};

export const INTRO_TECH_STACK: IntroTechItem[] = [
  { icon: "nodedotjs", label: "Node.js" },
  { icon: "nestjs", label: "NestJS" },
  { icon: "express", label: "Express" },
  { icon: "typescript", label: "TypeScript" },
  { icon: "javascript", label: "JavaScript" },
  { icon: "react", label: "React" },
  { icon: "nextdotjs", label: "Next.js" },
  { icon: "redux", label: "Redux" },
  { icon: "tailwindcss", label: "Tailwind CSS" },
  { icon: "mui", label: "Material UI" },
  { icon: "materialdesign", label: "Material Design" },
  { icon: "html5", label: "HTML5" },
  { icon: "css", label: "CSS3" },
  { icon: "sass", label: "Sass" },
  { icon: "vite", label: "Vite" },
  { icon: "webpack", label: "Webpack" },
  { icon: "astro", label: "Astro" },
  { icon: "postgresql", label: "PostgreSQL" },
  { icon: "mysql", label: "MySQL" },
  { icon: "mongodb", label: "MongoDB" },
  { icon: "redis", label: "Redis" },
  { icon: "prisma", label: "Prisma" },
  { icon: "supabase", label: "Supabase" },
  { icon: "firebase", label: "Firebase" },
  { icon: "graphql", label: "GraphQL" },
  { icon: "docker", label: "Docker" },
  { icon: "kubernetes", label: "Kubernetes" },
  { icon: "nginx", label: "Nginx" },
  { icon: "linux", label: "Linux" },
  { icon: "aws", label: "Amazon Web Services" },
  { icon: "vercel", label: "Vercel" },
  { icon: "git", label: "Git" },
  { icon: "github", label: "GitHub" },
  { icon: "gitlab", label: "GitLab" },
  { icon: "npm", label: "npm" },
  { icon: "pnpm", label: "pnpm" },
  { icon: "jest", label: "Jest" },
  { icon: "cypress", label: "Cypress" },
  { icon: "storybook", label: "Storybook" },
  { icon: "eslint", label: "ESLint" },
  { icon: "biome", label: "Biome" },
  { icon: "postman", label: "Postman" },
  { icon: "figma", label: "Figma" },
  { icon: "jira", label: "Jira" },
  { icon: "trello", label: "Trello" },
  { icon: "monday", label: "Monday.com" },
  { icon: "slack", label: "Slack" }
];
